package com.example.wizkid.model

data class Note(
    val id: String, // Or Long if using Room autogenerated ID
    val subjectId: String, // To link note to a subject
    val title: String,
    val content: String,
    val timestamp: Long = System.currentTimeMillis()
)